### ISSUE TITLE
Follow system theme if set to dark mode

### ISSUE THREAD

**Issue by ghost** [Fiddle-N/material-incognito-light-theme#1]
I configured Windows 10 to change the system theme to dark mode at night to reduce eye strain. It would be nice if your theme would change to dark mode too under that condition, but would remain light otherwise.

**Comment by Fiddle-N** [comment]
Unfortunately, I cannot do this. Themes are rather dumb, unfortunately, and are not system-aware. 

The best I can recommend is to uninstall my theme so that light mode and dark mode can go back to their defaults. Unfortunately, this will mean that Incognito Mode will always be dark.
