### ISSUE TITLE
stopped working 9/22/21

### ISSUE THREAD

**Issue by gitbuffet** [Fiddle-N/material-incognito-light-theme#2]
Spontaneously stopped working on startup 9/22/21.  It shows it is installed in google chrome (Version 94.0.4606.54 (Official Build) (64-bit) >settings> appearance, but does not work.  Incognito page and tabs are all black.  See similar reports in chrome web store.  Great theme, without it would go to Firefox.

**Comment by Fiddle-N** [comment]
Long story short - Google killed all incognito theme customisation back in September 2021. This is a deliberate choice on their part. I suspect this is the first step in killing all theme customisation, as you can now set themes colours from within Settings anyway, so there is no real reason to keep third-party themes around. However, there is no way to change the incognito theming through themes or through Settings - it will always be dark.

You can temporarily reverse this change by going to chrome://flags/#incognito-brand-consistency-for-desktop and setting to Disabled. However, Chrome flags do not stick around for long, especially those related to appearances. When the flag goes, the functionality will revert back.

These recent developments mean that Material Incognito Light Theme is officially deprecated. It will no longer be receiving any updates from now on. When the Chrome flag disappears, I will pull this theme from the Chrome Web Store shortly after, as it will serve essentially no purpose anymore.

Thank you for using my theme in the meantime; I hope you enjoyed it while it lasted.
