### ISSUE TITLE
stopped working 11/30/2021

### ISSUE THREAD

**Issue by dcouzin** [Fiddle-N/material-incognito-light-theme#3]
After 14 sunny days I'm back in the Chrome Incognito dungeon.

**Comment by Fiddle-N** [comment]
Long story short - Google killed all incognito theme customisation back in September 2021. This is a deliberate choice on their part. I suspect this is the first step in killing all theme customisation, as you can now set themes colours from within Settings anyway, so there is no real reason to keep third-party themes around. However, there is no way to change the incognito theming through themes or through Settings - it will always be dark.

You can temporarily reverse this change by going to chrome://flags/#incognito-brand-consistency-for-desktop and setting to Disabled. However, Chrome flags do not stick around for long, especially those related to appearances. When the flag goes, the functionality will revert back.

These recent developments mean that Material Incognito Light Theme is officially deprecated. It will no longer be receiving any updates from now on. When the Chrome flag disappears, I will pull this theme from the Chrome Web Store shortly after, as it will serve essentially no purpose anymore.

Thank you for using my theme in the meantime; I hope you enjoyed it while it lasted.

**Comment by dcouzin** [comment]
Dear Fiddle,
Thanks much for this information.  Strangely your theme plugin did work when I first installed it November.
Now your temporary workaround, with the flag, is working and what a pleasure it is to be able to scan through long lists of bookmark names displayed black-on-white.  
What was Google's reason for preventing black-on-white themes for Incognito?
Google makes less money from Incognito use.  It can dissuade sensitive users by tormenting them with white-on-black, while looking cool to a probably penniless fringe.  (I hope there is a less cynical explanation.)

Sincerely,
Dennis Couzin

**Comment by Fiddle-N** [comment]
From what I can tell, it's about delivering a consistent "Incognito" brand. Incognito isn't just a mode in Chrome anymore, it's a brand that is getting applied to other products, like Gboard. Keeping the colour always the same is part of that Incognito brand identity. 

I don't agree with the change, but it is what it is.

**Comment by dcouzin** [comment]
Dear Fiddle,
In my land today the Chrome shit hit the fan.  Incognito acquired a comically dysfunctional interface.  For the coolest users only.
Thanks for your help.
Dennis
